services:
  app:
    build:
      context: .
    ports:
      - '${PORT:-8000}:8000'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '${PORT:-80}:80'
    depends_on:
      - app
